# Generated by Django 3.2.2 on 2021-05-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
